apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/danieltech33/argocd-app-config.git
    targetRevision: HEAD
    path: services/service1
  destination:
    server: https://kubernetes.default.svc
    namespace: service1
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true 