apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/nanuchi/argocd-app-config.git
    targetRevision: HEAD
    path: services/service2
  destination:
    server: https://kubernetes.default.svc
    namespace: service2
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true 